substitutions:
  _FRONTEND_IMAGE_NAME: front-end
  _FRONTEND_IMAGE_TAG: '1'

  _ORDER_IMAGE_NAME: order-service
  _ORDER_IMAGE_TAG: '1'

  _CATALOG_IMAGE_NAME: catalog-service
  _CATALOG_IMAGE_TAG: '1'

  _CUSTOMER_IMAGE_NAME: customer-service
  _CUSTOMER_IMAGE_TAG: '1'

  # CHANGE THESE FOR PRODUCTION
  # _ENV: production
  # _MONGODB_FILE_PREFIX: mongodb-prod
  _ENV: staging
  _MONGODB_FILE_PREFIX: mongodb-stag

  # TODO: Pass these in as configuration arguments. Region and Cluster name are
  # subject to change and should not be hardcoded!
  # See <https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/kubectl>
  # for more information
  _CLUSTER_LOCATION=us-central1
  _CLUSTER_NAME=cicd-test-dt-kube-demo-cluster

steps:

- id: 'Deploy Mongodb'
  name: gcr.io/cloud-builders/kubectl
  args:
  - 'apply'
  - -f
  - $_MONGODB_FILE_PREFIX-configmaps.yml
  - -f
  - $_MONGODB_FILE_PREFIX-secrets.yml
  - -f
  - $_MONGODB_FILE_PREFIX-deploy.yml
  env:
  - 'CLOUDSDK_COMPUTE_REGION=$_CLUSTER_LOCATION'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

- id: 'Template Kube Config'
  name: gcr.io/cloud-builders/kubectl
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      sed -i 's/REPLACE_NAMESPACE/${_ENV}/g' front-end.yml
      sed -i 's/REPLACE_NAMESPACE/${_ENV}/g' order-end.yml
      sed -i 's/REPLACE_NAMESPACE/${_ENV}/g' customer-service.yml
      sed -i 's/REPLACE_NAMESPACE/${_ENV}/g' catalog-service.yml

      sed -i 's#REPLACE-IMAGE-NAME#gcr.io/$PROJECT_ID/${_FRONTEND_IMAGE_NAME}:${_FRONTEND_IMAGE_TAG}#g' front-end.yml
      sed -i 's#REPLACE-IMAGE-NAME#gcr.io/$PROJECT_ID/${_ORDER_IMAGE_NAME}:${_ORDER_IMAGE_TAG}#g' order-service.yml
      sed -i 's#REPLACE-IMAGE-NAME#gcr.io/$PROJECT_ID/${_CUSTOMER_IMAGE_NAME}:${_CUSTOMER_IMAGE_TAG}#g' customer-service.yml
      sed -i 's#REPLACE-IMAGE-NAME#gcr.io/$PROJECT_ID/${_CATALOG_IMAGE_NAME}:${_CATALOG_IMAGE_TAG}#g' catalog-service.yml
   
      cat front-end.yml
      cat order-service.yml
      cat customer-service.yml
      cat catalog-service.yml

- id: 'Deploy Frontend'
  name: gcr.io/cloud-builders/gke-deploy
  args:
  - run
  - --cluster=$_CLUSTER_NAME
  - --location=$_CLUSTER_LOCATION
  - --filename=front-end.yml
  - --image=gcr.io/$PROJECT_ID/$_FRONTEND_IMAGE_NAME:$_FRONTEND_IMAGE_TAG
  - --namespace=$_ENV

- id: 'Deploy Order Service'
  name: gcr.io/cloud-builders/gke-deploy
  args:
  - run
  - --cluster=$_CLUSTER_NAME
  - --location=$_CLUSTER_LOCATION
  - --filename=order-service.yml
  - --image=gcr.io/$PROJECT_ID/$_ORDER_SERVICE_IMAGE_NAME:$_ORDER_SERVICE_IMAGE_TAG
  - --namespace=$_ENV

- id: 'Deploy Customer Service'
  name: gcr.io/cloud-builders/gke-deploy
  args:
  - run
  - --cluster=$_CLUSTER_NAME
  - --location=$_CLUSTER_LOCATION
  - --filename=customer-service.yml
  - --image=gcr.io/$PROJECT_ID/$_CUSTOMER_SERVICE_IMAGE_NAME:$_CUSTOMER_SERVICE_IMAGE_TAG
  - --namespace=$_ENV

- id: 'Deploy Catalog Service'
  name: gcr.io/cloud-builders/gke-deploy
  args:
  - run
  - --cluster=$_CLUSTER_NAME
  - --location=$_CLUSTER_LOCATION
  - --filename=catalog-service.yml
  - --image=gcr.io/$PROJECT_ID/$_CATALOG_SERVICE_IMAGE_NAME:$_CATALOG_SERVICE_IMAGE_TAG
  - --namespace=$_ENV


# TODO: Enable the following steps
#- id: 'Show Pods'
#  name: gcr.io/cloud-builders/kubectl
#  args:
#  - get
#  - pods
#  - -n
#  - $_ENV
#
#- id: 'Health Check'
#- id: 'Push Dynatrace Deployment Event'
#- id: 'Run e2e load test'
#- id: 'quality gate'
