apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: order
  name: order
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      run: order
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: order
    spec:
      containers:
      - image: REPLACE-IMAGE-NAME
        name: order
        ports:
        - containerPort: 8080
        resources: {}
        imagePullPolicy: Always
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
        - name: ELASTIC_APM_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: apmserver
              key: service-name
        - name: ELASTIC_APM_APPLICATION_PACKAGES
          valueFrom:
            secretKeyRef:
              name: apmserver
              key: application-pack
        - name: ELASTIC_APM_SERVER_URLS
          valueFrom:
            secretKeyRef:
              name: apmserver
              key: server-urls
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: order
  name: order
  namespace: REPLACE_NAMESPACE
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: order
  type: LoadBalancer
status:
  loadBalancer: {}
